// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub pump_create_fee_changeds: ::prost::alloc::vec::Vec<PumpCreateFeeChanged>,
    #[prost(message, repeated, tag="2")]
    pub pump_fee_address_changeds: ::prost::alloc::vec::Vec<PumpFeeAddressChanged>,
    #[prost(message, repeated, tag="3")]
    pub pump_fee_ratios_changeds: ::prost::alloc::vec::Vec<PumpFeeRatiosChanged>,
    #[prost(message, repeated, tag="4")]
    pub pump_ip_share_changeds: ::prost::alloc::vec::Vec<PumpIpShareChanged>,
    #[prost(message, repeated, tag="5")]
    pub pump_new_tokens: ::prost::alloc::vec::Vec<PumpNewToken>,
    #[prost(message, repeated, tag="6")]
    pub pump_nutbox_allocation_parkeds: ::prost::alloc::vec::Vec<PumpNutboxAllocationParked>,
    #[prost(message, repeated, tag="7")]
    pub pump_nutbox_linkeds: ::prost::alloc::vec::Vec<PumpNutboxLinked>,
    #[prost(message, repeated, tag="8")]
    pub pump_ownership_transfer_starteds: ::prost::alloc::vec::Vec<PumpOwnershipTransferStarted>,
    #[prost(message, repeated, tag="9")]
    pub pump_ownership_transferreds: ::prost::alloc::vec::Vec<PumpOwnershipTransferred>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TokenEvents {
    #[prost(message, repeated, tag="1")]
    pub trades: ::prost::alloc::vec::Vec<TokenTrade>,
    #[prost(message, repeated, tag="2")]
    pub transfers: ::prost::alloc::vec::Vec<TokenTransfer>,
    #[prost(message, repeated, tag="3")]
    pub listed_to_dex: ::prost::alloc::vec::Vec<TokenListedToDex>,
    #[prost(message, repeated, tag="4")]
    pub swap_trades: ::prost::alloc::vec::Vec<TokenTrade>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IpShareEvents {
    #[prost(message, repeated, tag="1")]
    pub creates: ::prost::alloc::vec::Vec<IpShareCreate>,
    #[prost(message, repeated, tag="2")]
    pub trades: ::prost::alloc::vec::Vec<IpShareTrade>,
    #[prost(message, repeated, tag="3")]
    pub value_captures: ::prost::alloc::vec::Vec<IpShareValueCaptured>,
    #[prost(message, repeated, tag="4")]
    pub stakes: ::prost::alloc::vec::Vec<IpShareStake>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WalnutEvents {
    #[prost(message, repeated, tag="1")]
    pub events: ::prost::alloc::vec::Vec<WalnutEvent>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BasketRegistryEvents {
    #[prost(message, repeated, tag="1")]
    pub creations: ::prost::alloc::vec::Vec<BasketCreated>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BasketEvents {
    #[prost(message, repeated, tag="1")]
    pub trades: ::prost::alloc::vec::Vec<BasketTrade>,
    #[prost(message, repeated, tag="2")]
    pub operations: ::prost::alloc::vec::Vec<BasketOperation>,
    #[prost(message, repeated, tag="3")]
    pub fee_accruals: ::prost::alloc::vec::Vec<BasketFeeAccrual>,
    #[prost(message, repeated, tag="4")]
    pub fee_claims: ::prost::alloc::vec::Vec<BasketFeeClaim>,
    #[prost(message, repeated, tag="5")]
    pub auction_events: ::prost::alloc::vec::Vec<BasketAuctionEvent>,
    #[prost(message, repeated, tag="6")]
    pub rebalances: ::prost::alloc::vec::Vec<BasketRebalance>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BasketCreated {
    #[prost(string, tag="1")]
    pub evt_tx_hash: ::prost::alloc::string::String,
    #[prost(uint32, tag="2")]
    pub evt_index: u32,
    #[prost(message, optional, tag="3")]
    pub evt_block_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(uint64, tag="4")]
    pub evt_block_number: u64,
    #[prost(uint64, tag="5")]
    pub evt_ordinal: u64,
    #[prost(bytes="vec", tag="6")]
    pub basket: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="7")]
    pub creator: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="8")]
    pub registrar: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="9")]
    pub version: u32,
    #[prost(uint64, tag="10")]
    pub created_at: u64,
    #[prost(bytes="vec", tag="11")]
    pub salt: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="12")]
    pub evt_block_hash: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BasketTrade {
    #[prost(string, tag="1")]
    pub evt_tx_hash: ::prost::alloc::string::String,
    #[prost(uint32, tag="2")]
    pub evt_index: u32,
    #[prost(message, optional, tag="3")]
    pub evt_block_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(uint64, tag="4")]
    pub evt_block_number: u64,
    #[prost(uint64, tag="5")]
    pub evt_ordinal: u64,
    #[prost(bytes="vec", tag="6")]
    pub basket: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, tag="7")]
    pub is_buy: bool,
    #[prost(bytes="vec", tag="8")]
    pub payer: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="9")]
    pub recipient: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="10")]
    pub frontend: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="11")]
    pub usdg_amount: ::prost::alloc::string::String,
    #[prost(string, tag="12")]
    pub basket_amount: ::prost::alloc::string::String,
    #[prost(string, tag="13")]
    pub fee_weth: ::prost::alloc::string::String,
    #[prost(bool, tag="14")]
    pub routed: bool,
    #[prost(uint32, tag="15")]
    pub router_evt_index: u32,
    #[prost(bytes="vec", tag="16")]
    pub evt_block_hash: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BasketOperation {
    #[prost(string, tag="1")]
    pub kind: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub evt_tx_hash: ::prost::alloc::string::String,
    #[prost(uint32, tag="3")]
    pub evt_index: u32,
    #[prost(message, optional, tag="4")]
    pub evt_block_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(uint64, tag="5")]
    pub evt_block_number: u64,
    #[prost(uint64, tag="6")]
    pub evt_ordinal: u64,
    #[prost(bytes="vec", tag="7")]
    pub basket: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="8")]
    pub account: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="9")]
    pub recipient: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="10")]
    pub asset: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="11")]
    pub amount: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="12")]
    pub evt_block_hash: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BasketFeeAccrual {
    #[prost(string, tag="1")]
    pub evt_tx_hash: ::prost::alloc::string::String,
    #[prost(uint32, tag="2")]
    pub evt_index: u32,
    #[prost(message, optional, tag="3")]
    pub evt_block_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(uint64, tag="4")]
    pub evt_block_number: u64,
    #[prost(uint64, tag="5")]
    pub evt_ordinal: u64,
    #[prost(bytes="vec", tag="6")]
    pub basket: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="7")]
    pub holder_amount: ::prost::alloc::string::String,
    #[prost(string, tag="8")]
    pub auction_amount: ::prost::alloc::string::String,
    #[prost(string, tag="9")]
    pub creator_amount: ::prost::alloc::string::String,
    #[prost(string, tag="10")]
    pub launcher_amount: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="11")]
    pub frontend: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="12")]
    pub frontend_amount: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="13")]
    pub evt_block_hash: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BasketFeeClaim {
    #[prost(string, tag="1")]
    pub claim_type: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub evt_tx_hash: ::prost::alloc::string::String,
    #[prost(uint32, tag="3")]
    pub evt_index: u32,
    #[prost(message, optional, tag="4")]
    pub evt_block_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(uint64, tag="5")]
    pub evt_block_number: u64,
    #[prost(uint64, tag="6")]
    pub evt_ordinal: u64,
    #[prost(bytes="vec", tag="7")]
    pub basket: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="8")]
    pub beneficiary: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="9")]
    pub amount: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="10")]
    pub evt_block_hash: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BasketAuctionEvent {
    #[prost(string, tag="1")]
    pub kind: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub evt_tx_hash: ::prost::alloc::string::String,
    #[prost(uint32, tag="3")]
    pub evt_index: u32,
    #[prost(message, optional, tag="4")]
    pub evt_block_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(uint64, tag="5")]
    pub evt_block_number: u64,
    #[prost(uint64, tag="6")]
    pub evt_ordinal: u64,
    #[prost(string, tag="7")]
    pub auction_id: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="8")]
    pub account: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="9")]
    pub recipient: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="10")]
    pub amount: ::prost::alloc::string::String,
    #[prost(string, tag="11")]
    pub secondary_amount: ::prost::alloc::string::String,
    #[prost(string, tag="12")]
    pub spot_quote: ::prost::alloc::string::String,
    #[prost(string, tag="13")]
    pub initial_bid: ::prost::alloc::string::String,
    #[prost(uint64, tag="14")]
    pub end_time: u64,
    #[prost(bytes="vec", tag="15")]
    pub evt_block_hash: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BasketRebalance {
    #[prost(string, tag="1")]
    pub evt_tx_hash: ::prost::alloc::string::String,
    #[prost(uint32, tag="2")]
    pub evt_index: u32,
    #[prost(message, optional, tag="3")]
    pub evt_block_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(uint64, tag="4")]
    pub evt_block_number: u64,
    #[prost(uint64, tag="5")]
    pub evt_ordinal: u64,
    #[prost(bytes="vec", tag="6")]
    pub basket: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="7")]
    pub nav_before: ::prost::alloc::string::String,
    #[prost(string, tag="8")]
    pub nav_after: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="9")]
    pub evt_block_hash: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WalnutEvent {
    #[prost(string, tag="1")]
    pub kind: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub evt_tx_hash: ::prost::alloc::string::String,
    #[prost(uint32, tag="3")]
    pub evt_index: u32,
    #[prost(message, optional, tag="4")]
    pub evt_block_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(uint64, tag="5")]
    pub evt_block_number: u64,
    #[prost(uint64, tag="6")]
    pub evt_ordinal: u64,
    #[prost(bytes="vec", tag="7")]
    pub contract: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="8")]
    pub community: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="9")]
    pub pool: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="10")]
    pub account: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="11")]
    pub asset: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="12")]
    pub secondary_account: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="13")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="14")]
    pub amount: ::prost::alloc::string::String,
    #[prost(string, tag="15")]
    pub secondary_amount: ::prost::alloc::string::String,
    #[prost(bool, tag="16")]
    pub flag: bool,
    #[prost(uint32, tag="17")]
    pub ratio: u32,
    #[prost(bytes="vec", repeated, tag="18")]
    pub pools: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint32, repeated, tag="19")]
    pub ratios: ::prost::alloc::vec::Vec<u32>,
    #[prost(bytes="vec", tag="20")]
    pub operator: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="21")]
    pub pool_factory: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="22")]
    pub evt_block_hash: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IpShareCreate {
    #[prost(string, tag="1")]
    pub evt_tx_hash: ::prost::alloc::string::String,
    #[prost(uint32, tag="2")]
    pub evt_index: u32,
    #[prost(message, optional, tag="3")]
    pub evt_block_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(uint64, tag="4")]
    pub evt_block_number: u64,
    #[prost(bytes="vec", tag="5")]
    pub subject: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="6")]
    pub amount: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub create_fee: ::prost::alloc::string::String,
    #[prost(uint64, tag="8")]
    pub evt_ordinal: u64,
    #[prost(bytes="vec", tag="9")]
    pub evt_block_hash: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IpShareTrade {
    #[prost(string, tag="1")]
    pub evt_tx_hash: ::prost::alloc::string::String,
    #[prost(uint32, tag="2")]
    pub evt_index: u32,
    #[prost(message, optional, tag="3")]
    pub evt_block_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(uint64, tag="4")]
    pub evt_block_number: u64,
    #[prost(bytes="vec", tag="5")]
    pub trader: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="6")]
    pub subject: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, tag="7")]
    pub is_buy: bool,
    #[prost(string, tag="8")]
    pub share_amount: ::prost::alloc::string::String,
    #[prost(string, tag="9")]
    pub eth_amount: ::prost::alloc::string::String,
    #[prost(string, tag="10")]
    pub protocol_eth_amount: ::prost::alloc::string::String,
    #[prost(string, tag="11")]
    pub subject_eth_amount: ::prost::alloc::string::String,
    #[prost(string, tag="12")]
    pub supply: ::prost::alloc::string::String,
    #[prost(uint64, tag="13")]
    pub evt_ordinal: u64,
    #[prost(bytes="vec", tag="14")]
    pub evt_block_hash: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IpShareValueCaptured {
    #[prost(string, tag="1")]
    pub evt_tx_hash: ::prost::alloc::string::String,
    #[prost(uint32, tag="2")]
    pub evt_index: u32,
    #[prost(message, optional, tag="3")]
    pub evt_block_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(uint64, tag="4")]
    pub evt_block_number: u64,
    #[prost(bytes="vec", tag="5")]
    pub subject: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="6")]
    pub investor: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="7")]
    pub amount: ::prost::alloc::string::String,
    #[prost(uint64, tag="8")]
    pub evt_ordinal: u64,
    #[prost(bytes="vec", tag="9")]
    pub evt_block_hash: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IpShareStake {
    #[prost(string, tag="1")]
    pub evt_tx_hash: ::prost::alloc::string::String,
    #[prost(uint32, tag="2")]
    pub evt_index: u32,
    #[prost(message, optional, tag="3")]
    pub evt_block_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(uint64, tag="4")]
    pub evt_block_number: u64,
    #[prost(bytes="vec", tag="5")]
    pub staker: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="6")]
    pub subject: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, tag="7")]
    pub is_stake: bool,
    #[prost(string, tag="8")]
    pub amount: ::prost::alloc::string::String,
    #[prost(string, tag="9")]
    pub staked_amount: ::prost::alloc::string::String,
    #[prost(uint64, tag="10")]
    pub evt_ordinal: u64,
    #[prost(bytes="vec", tag="11")]
    pub evt_block_hash: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TokenTrade {
    #[prost(string, tag="1")]
    pub evt_tx_hash: ::prost::alloc::string::String,
    #[prost(uint32, tag="2")]
    pub evt_index: u32,
    #[prost(message, optional, tag="3")]
    pub evt_block_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(uint64, tag="4")]
    pub evt_block_number: u64,
    #[prost(bytes="vec", tag="5")]
    pub token: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="6")]
    pub buyer: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="7")]
    pub sellsman: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, tag="8")]
    pub is_buy: bool,
    #[prost(string, tag="9")]
    pub token_amount: ::prost::alloc::string::String,
    #[prost(string, tag="10")]
    pub eth_amount: ::prost::alloc::string::String,
    #[prost(string, tag="11")]
    pub tiptag_fee: ::prost::alloc::string::String,
    #[prost(string, tag="12")]
    pub sellsman_fee: ::prost::alloc::string::String,
    #[prost(uint64, tag="13")]
    pub evt_ordinal: u64,
    #[prost(string, tag="14")]
    pub price: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="15")]
    pub evt_block_hash: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TokenTransfer {
    #[prost(string, tag="1")]
    pub evt_tx_hash: ::prost::alloc::string::String,
    #[prost(uint32, tag="2")]
    pub evt_index: u32,
    #[prost(message, optional, tag="3")]
    pub evt_block_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(uint64, tag="4")]
    pub evt_block_number: u64,
    #[prost(bytes="vec", tag="5")]
    pub token: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="6")]
    pub from: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="7")]
    pub to: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="8")]
    pub amount: ::prost::alloc::string::String,
    #[prost(uint64, tag="9")]
    pub evt_ordinal: u64,
    #[prost(bytes="vec", tag="10")]
    pub evt_block_hash: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TokenListedToDex {
    #[prost(string, tag="1")]
    pub evt_tx_hash: ::prost::alloc::string::String,
    #[prost(uint32, tag="2")]
    pub evt_index: u32,
    #[prost(message, optional, tag="3")]
    pub evt_block_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(uint64, tag="4")]
    pub evt_block_number: u64,
    #[prost(bytes="vec", tag="5")]
    pub token: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="6")]
    pub event_token: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="7")]
    pub pool_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="8")]
    pub sqrt_price_x96: ::prost::alloc::string::String,
    #[prost(uint64, tag="9")]
    pub evt_ordinal: u64,
    #[prost(bytes="vec", tag="10")]
    pub evt_block_hash: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PumpCreateFeeChanged {
    #[prost(string, tag="1")]
    pub evt_tx_hash: ::prost::alloc::string::String,
    #[prost(uint32, tag="2")]
    pub evt_index: u32,
    #[prost(message, optional, tag="3")]
    pub evt_block_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(uint64, tag="4")]
    pub evt_block_number: u64,
    #[prost(string, tag="5")]
    pub old_fee: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub new_fee: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PumpFeeAddressChanged {
    #[prost(string, tag="1")]
    pub evt_tx_hash: ::prost::alloc::string::String,
    #[prost(uint32, tag="2")]
    pub evt_index: u32,
    #[prost(message, optional, tag="3")]
    pub evt_block_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(uint64, tag="4")]
    pub evt_block_number: u64,
    #[prost(bytes="vec", tag="5")]
    pub old_address: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="6")]
    pub new_address: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PumpFeeRatiosChanged {
    #[prost(string, tag="1")]
    pub evt_tx_hash: ::prost::alloc::string::String,
    #[prost(uint32, tag="2")]
    pub evt_index: u32,
    #[prost(message, optional, tag="3")]
    pub evt_block_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(uint64, tag="4")]
    pub evt_block_number: u64,
    #[prost(string, tag="5")]
    pub donut_fee: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub sellsman_fee: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PumpIpShareChanged {
    #[prost(string, tag="1")]
    pub evt_tx_hash: ::prost::alloc::string::String,
    #[prost(uint32, tag="2")]
    pub evt_index: u32,
    #[prost(message, optional, tag="3")]
    pub evt_block_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(uint64, tag="4")]
    pub evt_block_number: u64,
    #[prost(bytes="vec", tag="5")]
    pub old_ip_share: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="6")]
    pub new_ip_share: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PumpNewToken {
    #[prost(string, tag="1")]
    pub evt_tx_hash: ::prost::alloc::string::String,
    #[prost(uint32, tag="2")]
    pub evt_index: u32,
    #[prost(message, optional, tag="3")]
    pub evt_block_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(uint64, tag="4")]
    pub evt_block_number: u64,
    #[prost(string, tag="5")]
    pub tick: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="6")]
    pub token: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="7")]
    pub creator: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="8")]
    pub evt_ordinal: u64,
    #[prost(bytes="vec", tag="9")]
    pub evt_block_hash: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PumpNutboxAllocationParked {
    #[prost(string, tag="1")]
    pub evt_tx_hash: ::prost::alloc::string::String,
    #[prost(uint32, tag="2")]
    pub evt_index: u32,
    #[prost(message, optional, tag="3")]
    pub evt_block_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(uint64, tag="4")]
    pub evt_block_number: u64,
    #[prost(bytes="vec", tag="5")]
    pub token: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="6")]
    pub hook: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="7")]
    pub amount: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PumpNutboxLinked {
    #[prost(string, tag="1")]
    pub evt_tx_hash: ::prost::alloc::string::String,
    #[prost(uint32, tag="2")]
    pub evt_index: u32,
    #[prost(message, optional, tag="3")]
    pub evt_block_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(uint64, tag="4")]
    pub evt_block_number: u64,
    #[prost(bytes="vec", tag="5")]
    pub token: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="6")]
    pub community: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="7")]
    pub social_pool: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PumpOwnershipTransferStarted {
    #[prost(string, tag="1")]
    pub evt_tx_hash: ::prost::alloc::string::String,
    #[prost(uint32, tag="2")]
    pub evt_index: u32,
    #[prost(message, optional, tag="3")]
    pub evt_block_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(uint64, tag="4")]
    pub evt_block_number: u64,
    #[prost(bytes="vec", tag="5")]
    pub previous_owner: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="6")]
    pub new_owner: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PumpOwnershipTransferred {
    #[prost(string, tag="1")]
    pub evt_tx_hash: ::prost::alloc::string::String,
    #[prost(uint32, tag="2")]
    pub evt_index: u32,
    #[prost(message, optional, tag="3")]
    pub evt_block_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(uint64, tag="4")]
    pub evt_block_number: u64,
    #[prost(bytes="vec", tag="5")]
    pub previous_owner: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="6")]
    pub new_owner: ::prost::alloc::vec::Vec<u8>,
}
// @@protoc_insertion_point(module)
